### ISSUE TITLE
The demo does not start if a redis server runs locally

### ISSUE THREAD

**Issue by j75** [dsibilio/rsocket-demo#1]
First of all, you forgot to mention that the demo starts a redis server, in this case one should either stop it or modify the port chosen in 
src/main/resources/application.yml

**Comment by dsibilio** [comment]
Thanks for the feedback, there is actually a *very tiny* reference to an embedded Redis server being started in the [Running with Docker](https://github.com/dsibilio/rsocket-demo/blob/master/README.md#running-with-docker) section.

I'll update the README so that it is clear that the demo starts an embedded redis server on the specified port.

Ty again :+1:

**Comment by dsibilio** [comment]
PS. You should also be able to run the demo disabling the Embedded Redis server by enabling the prod profile (eg. `mvn spring-boot:run -Dspring-boot.run.profiles=prod`)

**Comment by dsibilio** [comment]
Updated the docs with https://github.com/dsibilio/rsocket-demo/commit/a0a427c3efa6fe111f8993bd1d12594506d37266

I'll go ahead and close this, feel free to contact me for any other issues.
