### ISSUE TITLE
Why isn't index.js actually run by docker ?

### ISSUE THREAD

**Issue by LifeIsStrange** [dsibilio/rsocket-demo#3]
We have lost some time and really WTFed when we observed that the changes we did on the index.js nor the app.js file actually unaffected the localhost:8080 output, because they are not run.

Is the file actually being run on a remote server ? If so, why, and is it the same as the local app.js file?

*How* can we run the local app.js file instead of the remote file in order to observe our changes thus allowing us to better learn how to use rsocket ?

**Comment by dsibilio** [comment]
Hey! The page is not being served remotely of course. 
The thing is that the [index.js](https://github.com/dsibilio/rsocket-demo/tree/master/src/main/js) file you see right under _src/main/js_ relies on the usage of npm's require function and therefore would need a Node.js server to work correctly. Since we're not using any Node.js server here, but relying on the HTTP server thas is embedded within Spring Boot (Netty), we cannot rely on the usage of the require function. 
The index.js file has been browserified into the app.js file thanks to http://browserify.org/ and is the actual file that is being served along with the index.html file under the _src/main/resources/public/_ folder. 
Changes to [src/main/resources/public/app.js](https://github.com/dsibilio/rsocket-demo/blob/master/src/main/resources/public/app.js) and [src/main/resources/public/index.html](https://github.com/dsibilio/rsocket-demo/blob/master/src/main/resources/public/index.html) should most definitely be reflected!

P.S. most of this stuff is also explained in my article that features this demo and explains how to build a similar project bit by bit, at the following link: https://medium.com/@domenicosibilio/rsocket-with-spring-boot-js-zero-to-hero-ef63128f973d#bb08 😉

**Comment by LifeIsStrange** [comment]
Thank you for taking your time for us, you are a great human being!

**Comment by dsibilio** [comment]
Thank you for your kind words 😄
